//ajax的url

//var newBookfunc_url= "json/newbook.js";
//var hotBookfunc_url= "json/newbook.js";
//var bookTypefunc_url= "json/bookType.js";
//var bookDetailfunc_url= "json/bookdetail.js";
//var bookTypeDetailfunc_url= "json/bookTypeDetail.js";
//var shoppingCarfunc_url= "json/shoppingCar.js";
//var movetolikefunc_url= "json/success.js";
//var delCarfunc_url= "json/success.js";
//var changeBookNumfunc_url= "json/success.js";
//var addLikeOrCartfunc_url= "json/success.js";
//var searchReaultfunc_url= "json/bookTypeDetail.js";
//var mylikefunc_url= "json/shoppingCar.js";
//var dellikefunc_url= "json/success.js";
//var okbuyfunc_url= "json/success.js";
//var myorderfunc_url= "json/myorder.js";
//var loginfunc_url="json/success.js"
//var registerfunc_url="json/success.js"
//var recommendBookfunc_url="json/newbook.js"
//var bookhavereadfunc_url="json/newbook.js"
//var guessyoulikefunc_url="json/newbook.js"
//var myselffunc_url="json/newbook.js"
//var setmyselffunc_url="";
//var setpwdfunc_url="";//修改密码

var newBookfunc_url= "newBook.do";//首页新书上线
var hotBookfunc_url= "hotBook.do";//首页热销图书
var bookTypefunc_url= "bookCategory.do";//图书分类
var bookDetailfunc_url= "bookDetailContent.do";//图书详情
var bookTypeDetailfunc_url= "bookTypeDetail.do";//图书分类书列表
var shoppingCarfunc_url= "shoppingCart.do";//购物车列表
var movetolikefunc_url= "movetoLike.do";//购物车移到我的收藏
var delCarfunc_url= "delCart.do";//购物车删除商品
var changeBookNumfunc_url= "changBookNum.do";//购物车改变商品数量
var addLikeOrCartfunc_url= "addLikeOrCart.do";//加入收藏或者购物车
var searchReaultfunc_url= "searchBook.do";//搜索接口列表
var mylikefunc_url= "collect.do";//收藏夹列表
var dellikefunc_url= "delCollect.do";//收藏夹删除商品
var okbuyfunc_url= "addOrder.do";//订单增加
var myorderfunc_url= "order.do";//我的订单
var loginfunc_url="userLogin.do";//登录
var registerfunc_url="userRegister.do";//注册
var recommendBookfunc_url="recommendBook.do";//推荐图书
var bookhavereadfunc_url="recommendBookDetail.do"//已浏览过图书(详情页)
var guessyoulikefunc_url="recommendBookLike.do";//猜你喜欢
var myselffunc_url="userSelf.do";//个人信息
var setmyselffunc_url="userSelfReset.do";//修改个人信息
var setpwdfunc_url="userPwdReset.do";//修改密码